### ISSUE TITLE
Mailgun supports htmlonly for tracking-clicks but your wrapper does not

### ISSUE THREAD

**Issue by gpickin** [mjclemente/mailgun.cfc#6]
Your module tries to eval as a boolean, and `htmlonly` errors

**Comment by mjclemente** [comment]
Good catch; definitely an issue. 

I honestly really don't like the way that I have the module set up, in that regard. It was the first that I wrote, and the data-checking that it's doing is really not terribly helpful and causes more problems than it's worth I think.

Since the field isn't actually boolean, I'll try just removing the check. Just need to make sure that CF handles the true/false values correctly then.

**Comment by mjclemente** [comment]
@gpickin Was just digging into this a bit. Just curious. Do you know what that option does? 

That is to say, is it possible to have click tracking for plaintext emails? When I have click-tracking set to true, URLs don't seem to be changed in the plaintext version of the emails, like they are in the HTML version. I'm going to create a support ticket to ask them to clarify this, but I was just wondering if you could shed any light on it.

Thanks!

**Comment by gpickin** [comment]
No clue.

https://documentation.mailgun.com/en/latest/user_manual.html#tracking-clicks
Thats the docs on it. I think if you do HTML and PLAIN it might re-write only the html version this way. 

Not sure to be honest.

I'm writing a wrapper for your module for cbmailservices. Posting it shortly.

**Comment by mjclemente** [comment]
Yeah. I saw that in the API docs too, but that's not the behavior I'm seeing. I opened a ticket with them to see if they could clarify. In the meantime I'll just remove the boolean check for the field.

**Comment by mjclemente** [comment]
Should be working in 0.5.1 

Cheers!
